server.port=8085
# Connexion à MySQL de XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/E-BANK?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
# Hibernate pour créer les tables automatiquement
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true